export const PAGE_NAMES: Record<string, string> = {
  'about': 'عن الشركة',
  'contact': 'تواصل معنا',
  'blog': 'المدونة',
  'alexandria': 'خدماتنا في الإسكندرية',
  'cairo': 'خدماتنا في القاهرة',
  'privacy': 'سياسة الخصوصية',
  'terms': 'الشروط والأحكام',
  'printing': 'خدمات الطباعة',
  'offset': 'طباعة أوفست',
  'digital': 'طباعة رقمية',
  'banners': 'طباعة بنرات',
  'business-cards': 'كروت شخصية وبروشورات',
  'uv': 'طباعة UV',
  'gifts': 'طباعة هدايا وأكواب',
  'copiers': 'ماكينات التصوير',
  'copiers/buy': 'بيع ماكينات التصوير',
  'buy': 'بيع ماكينات التصوير',
  'printers': 'طابعات للبيع',
  'maintenance': 'صيانة',
  'cartridges': 'كارتريدج وأحبار',
  'cameras': 'كاميرات المراقبة',
  'install': 'تركيب كاميرات',
  'dvr-nvr': 'أنظمة DVR و NVR',
  'ip-wifi': 'كاميرات IP وواي فاي',
  'ac': 'تكييفات',
  'ac/buy': 'تكييفات للبيع',
  'installation': 'تركيب تكييفات',
  'cash-machines': 'ماكينات الفارم والعد',
  'counting': 'ماكينات عد النقود',
  'detector': 'كشف العملات المزيفة',
  'franking': 'ماكينات الفارم والختم',
  'shredder': 'تدمير المستندات',
  'office-supplies': 'مستلزمات مكتبية',
  'a4-paper': 'ورق A4',
  'thermal': 'ورق حراري',
  'pens': 'أقلام وأدوات كتابة',
  'notebooks': 'دفاتر ومفكرات',
  'files': 'ملفات وأرشفة',
  'stamps': 'أختام مطاطية',
  'envelopes': 'أظرف وتغليف',
  'whiteboards': 'وايت بورد',
  'binding': 'دباسة ومشابك',
  'sticky-notes': 'بوست إت',
  'batteries-usb': 'بطاريات وUSB',
};
